"""test_regression_quality.py — CI-enforced retrieval regression gate.

This test runs the REAL BM25 retrieval engine (src.legal_ai.retrieval.bm25)
against the REAL legal corpus (legal_documents.json) and a reproducible,
seeded self-retrieval evaluation set (data/evaluation/eval_queries.json,
generated by scripts/build_eval_set.py — see that script for methodology
and limitations).

If this test is failing, retrieval quality has genuinely regressed — do not
raise the tolerance or delete this test to make CI green; investigate the
change that lowered the score first.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.legal_ai.evaluation.baseline import SELF_RETRIEVAL_SMOKE_BASELINE
from scripts.regression_harness import run_harness

DOCUMENTS_PATH = ROOT / "legal_documents.json"
EVAL_SET_PATH = ROOT / "data" / "evaluation" / "eval_queries.json"


@pytest.fixture(scope="module")
def measured_report():
    if not DOCUMENTS_PATH.exists():
        pytest.skip(f"corpus not found at {DOCUMENTS_PATH}")
    if not EVAL_SET_PATH.exists():
        pytest.skip(
            f"evaluation set not found at {EVAL_SET_PATH} — run "
            "`python scripts/build_eval_set.py` first"
        )
    return run_harness(DOCUMENTS_PATH, EVAL_SET_PATH)


def test_eval_set_is_nontrivial(measured_report):
    """Guard against the eval set silently shrinking to (near) nothing."""
    assert measured_report["eval_set_size"] >= 20, (
        "Evaluation set is suspiciously small — this gate becomes meaningless "
        "below ~20 queries. Regenerate with scripts/build_eval_set.py."
    )


def test_corpus_is_nontrivial(measured_report):
    """Guard against accidentally testing against a tiny/synthetic corpus again."""
    assert measured_report["corpus_documents"] >= 100, (
        "Corpus has fewer than 100 documents — this looks like a synthetic "
        "fixture, not the real legal_documents.json corpus."
    )


@pytest.mark.parametrize(
    "metric_key,baseline_attr",
    [
        ("MRR", "mrr"),
        ("Recall@1", "recall_at_1"),
        ("Recall@3", "recall_at_3"),
        ("Recall@5", "recall_at_5"),
        ("Recall@10", "recall_at_10"),
    ],
)
def test_retrieval_meets_smoke_baseline(measured_report, metric_key, baseline_attr):
    measured = measured_report["metrics"][metric_key]
    floor = getattr(SELF_RETRIEVAL_SMOKE_BASELINE, baseline_attr)
    tolerance = 0.01
    assert measured >= floor - tolerance, (
        f"{metric_key} regressed: measured={measured:.4f}, floor={floor:.4f}. "
        f"Run `python scripts/regression_harness.py` locally and inspect what changed."
    )
